Fix bug when checking if containers successfully started

diff --git a/.github/workflows/pipeline-ci.yml b/.github/workflows/pipeline-ci.yml
--- a/.github/workflows/pipeline-ci.yml
+++ b/.github/workflows/pipeline-ci.yml
@@ -64,6 +64,8 @@ jobs:
           db_logs=$(docker logs todolist-db)
           echo "$db_logs"
           if echo "$db_logs" | grep -q "database system is ready to accept connections"; then
+            echo "Database container started successfully"
+          else
             echo "Error : Problem while trying to start database container, check logs"
             exit 1
           fi
@@ -79,19 +81,16 @@ jobs:
         run: |
           front_logs=$(docker logs todolist-front)
           echo "$front_logs"
-          if echo "$front_logs" | grep -q "Local:" || ! echo "$front_logs" | grep -q "Network:"; then
-            echo "Error: todolist-front container did not start successfully"
-            exit 1 # Arrêter le workflow avec un code de sortie 1
-          fi
-          
+          if echo "$front_logs" | grep -q "Local:" || echo "$front_logs" | grep -q "Network:"; then
+            echo "Client container started successfully"
+          else
+            echo "Error: Problem while trying to start client container, check logs"
+            exit 1
+          fi         
 
-  test_job_3:
-    name: Test Job 3
+  build_and_test_client:
+    name: Build and Test ReactJS Client
     runs-on: ubuntu-latest
     steps:
       - name: Run echo command
-        run: echo "Running Test Job 3"
-    # - name: Test
-    #   run: go test -v ./...
-  
-          
+        run: echo "Running Test Job 3"          
